### ISSUE TITLE
Would like Scratch3 for i386

### ISSUE THREAD

**Issue by mobluse** [flathub/edu.mit.Scratch#15]
I run [Debian Buster with Raspberry Pi Desktop](https://www.raspberrypi.org/software/raspberry-pi-desktop/) on an Eee PC 1001HA netbook with [Atom N270](https://ark.intel.com/content/www/us/en/ark/products/36331/intel-atom-processor-n270-512k-cache-1-60-ghz-533-mhz-fsb.html) x86-32 only and it would need support for architecture i386 in order to run (i386 is actually compiled as i686 AFAIK).

**Comment by refi64** [comment]
The freedesktop runtime we use has dropped support for 32-bit platforms, so there's not much that can be done here. Sorry!
