### ISSUE TITLE
No ARM support

### ISSUE THREAD

**Issue by wjt** [flathub/edu.mit.Scratch#3]
This Flatpak is currently built only for x86_64. Endless is interested in two flavours of ARM:

* We have production armhf (32-bit) devices. Our old in-house Flatpak of a much older version of Scratch was built for armhf.
* We hope to start shipping arm64 images soon.

In IRC discussion about the x86_64-only limitation, @refi64 explained

> it's because the build steps use chromedriver which only has official binaries for x64, if there's need for it I can e.g. pull Fedora's binaries for other architectures but at the moment it didn't seem critical

**Comment by jgarciao** [comment]
Maybe as temporally solution for armhf the .deb files from raspbian could be used as extra-data:
- https://www.raspberrypi.org/blog/scratch-3-desktop-for-raspbian-on-raspberry-pi/
- http://archive.raspberrypi.org/debian/pool/main/s/scratch3/
