### ISSUE TITLE
Bundles libffmpeg.so containing patent-encumbered codecs

### ISSUE THREAD

**Issue by wjt** [flathub/edu.mit.Scratch#6]
```
$ strings /app/scratch/libffmpeg.so | grep ff_h264 | wc -l
133
$ strings /app/scratch/libffmpeg.so | grep ff_aac | wc -l
36
```

https://www.npmjs.com/package/electron-packager-plugin-non-proprietary-codecs-ffmpeg appears to exist. Internally, it just grabs an ffmpeg binary from https://github.com/electron/electron/releases/tag/v6.1.7 and these appear not to have patent-encumbered codecs, though I can find no information about how they are compiled which does not exactly inspire confidence.

**Comment by refi64** [comment]
With the non-patented ffmpeg:

```
[📦 edu.mit.Scratch scratch]$ strings /app/scratch/libffmpeg.so  | grep ff_h264
ff_h264_profiles
ff_h264_pred_init
ff_h264_pred_init_x86
[📦 edu.mit.Scratch scratch]$ strings /app/scratch/libffmpeg.so | grep ff_aac
ff_aac_profiles
[📦 edu.mit.Scratch scratch]$ 
```

These are probably just some small stubs.
